# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - myyotubeapi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm install serverless
        serverless create --name myYoutubeApi --template aws-nodejs --path myYoutubeService
        cd myYoutubeService
        serverless deploy --stage prd

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myyotubeapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aedd8c1b67ed46c5a22bad3ec5d55299 }}
        package: .
